### ISSUE TITLE
Pre processing macros

### ISSUE THREAD

**Issue by TeiturMcSwagger** [CTxD/FreeTACOS#27]
There is missing a non ad hoc way to use pre-processsing macros.

Proposed solution: Add a field in the xml file for macros that will be used to control pre-processing in in the scala and c++ code.

The following pre-processing macros need to be added:
- multi/single core  mode
- debugging mode

**Comment by CTxD** [comment]
@TeiturMcSwagger, Didn't you fix this? Can the issue be resolved?
